import { useState, useEffect } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { motion } from "framer-motion";
import {
  FileText,
  Scale,
  ShieldCheck,
  CheckCircle2,
  AlertTriangle,
  CreditCard,
  Lock,
  UserCheck,
  Building2,
  Mail,
  MapPin,
  HelpCircle,
  ChevronRight,
  ArrowUp,
  AlertCircle,
  Gavel,
  BookOpen,
  DollarSign,
  Server,
  FileCheck
} from "lucide-react";
import { Header } from "@/components/site/Header";
import { Footer } from "@/components/site/Footer";
import { ProductModeProvider } from "@/lib/product-mode";

export const Route = createFileRoute("/terms-and-conditions")({
  head: () => ({
    meta: [
      { title: "Terms & Conditions | SignAny 2.0 eSignature Platform" },
      {
        name: "description",
        content:
          "Read the Terms and Conditions governing your use of SignAny 2.0. Detailed terms on electronic signatures, user obligations, billing, and legal rights.",
      },
      { property: "og:title", content: "Terms & Conditions | SignAny 2.0" },
      {
        property: "og:description",
        content:
          "Read the Terms and Conditions governing your use of SignAny 2.0. Detailed terms on electronic signatures, user obligations, billing, and legal rights.",
      },
      { property: "og:type", content: "article" },
      { property: "og:url", content: "/terms-and-conditions" },
    ],
    links: [{ rel: "canonical", href: "/terms-and-conditions" }],
  }),
  component: TermsAndConditionsRoute,
});

function TermsAndConditionsRoute() {
  return (
    <ProductModeProvider>
      <TermsAndConditions />
    </ProductModeProvider>
  );
}

const ease = [0.2, 0, 0, 1] as const;

const tableOfContents = [
  { id: "acceptance", title: "1. Acceptance & Scope" },
  { id: "definitions", title: "2. Key Definitions" },
  { id: "eligibility", title: "3. Eligibility Requirements" },
  { id: "consumer-disclosure", title: "4. Consumer Disclosure & Consent" },
  { id: "account-responsibilities", title: "5. Account Responsibilities" },
  { id: "license-grant", title: "6. License Grant & Restrictions" },
  { id: "user-responsibilities", title: "7. Your Responsibilities" },
  { id: "role-of-service", title: "8. Role & Signature Validity" },
  { id: "freemium", title: "9. Free & Paid Tiers" },
  { id: "payment-billing", title: "10. Payment & Billing Terms" },
  { id: "storage-retention", title: "11. Document Storage & Retention" },
  { id: "acceptable-use", title: "12. Acceptable Use Policy" },
  { id: "intellectual-property", title: "13. Intellectual Property" },
  { id: "confidentiality", title: "14. Confidentiality Obligations" },
  { id: "disclaimers", title: "15. Warranty Disclaimers" },
  { id: "limitation-liability", title: "16. Limitation of Liability" },
  { id: "indemnification", title: "17. Indemnification" },
  { id: "termination", title: "18. Term & Termination" },
  { id: "dispute-resolution", title: "19. Dispute Resolution & Law" },
  { id: "general-provisions", title: "20. General Provisions" },
  { id: "supplemental-india", title: "21. Supplemental Terms for India" },
  { id: "contact-us", title: "22. Contact Information" },
];

const definitionsList = [
  { term: "Account", desc: "A registered user profile created to access the Service." },
  { term: "Authorised User", desc: "An individual permitted to use an Account, whether the Account holder or someone acting on their behalf with permission." },
  { term: "Document", desc: "Any digital file uploaded, sent, or signed through the Service." },
  { term: "Signature Data", desc: "Any typed, drawn, or uploaded signature image submitted through the Service." },
  { term: "Audit Trail", desc: "The record of signing actions, timestamps, IP addresses, consent logs, and cryptographic metadata generated by the Service in connection with a Document." },
  { term: "Paid Features", desc: "Functionality accessible only to users on a paid subscription tier." },
];

function TermsAndConditions() {
  const [activeSection, setActiveSection] = useState<string>("acceptance");
  const [showBackToTop, setShowBackToTop] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setShowBackToTop(window.scrollY > 400);

      const sectionElements = tableOfContents.map((item) => ({
        id: item.id,
        el: document.getElementById(item.id),
      }));

      const scrollPosition = window.scrollY + 200;

      for (let i = sectionElements.length - 1; i >= 0; i--) {
        const sec = sectionElements[i];
        if (sec.el && sec.el.offsetTop <= scrollPosition) {
          setActiveSection(sec.id);
          break;
        }
      }
    };

    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      const offset = 100;
      const bodyRect = document.body.getBoundingClientRect().top;
      const elementRect = element.getBoundingClientRect().top;
      const elementPosition = elementRect - bodyRect;
      const offsetPosition = elementPosition - offset;

      window.scrollTo({
        top: offsetPosition,
        behavior: "smooth",
      });
      setActiveSection(id);
    }
  };

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header />

      <main className="flex-1 pt-28 md:pt-36 pb-20">
        <div className="section-shell">
          {/* Hero Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease }}
            className="text-center max-w-4xl mx-auto mb-16"
          >
            {/* <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-secondary/10 text-secondary text-xs font-bold uppercase tracking-widest mb-4">
              <Scale size={16} />
              Legal Agreement
            </div> */}
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight text-foreground mb-6">
              Terms and Conditions
            </h1>
            <p className="text-muted-foreground text-base md:text-lg leading-relaxed max-w-2xl mx-auto">
              Please read these terms carefully before accessing or using SignAny 2.0. These Terms form a legally binding contract between you and MV Clouds Private Limited.
            </p>

            <div className="mt-6 inline-flex flex-wrap items-center justify-center gap-4 text-xs text-muted-foreground bg-muted/40 border border-border px-4 py-2 rounded-xl">
              <span><strong>Last Modified Date:</strong> 7 August 2026</span>
              {/* <span className="hidden sm:inline">•</span>
              <span><strong>Operator:</strong> MV Clouds Private Limited</span>
              <span className="hidden sm:inline">•</span>
              <span><strong>Platform:</strong> SignAny 2.0</span> */}
            </div>
          </motion.div>

          {/* Important Notice Callout Banner */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1, ease }}
            className="p-6 rounded-2xl bg-destructive/5 border border-destructive/20 mb-16 flex items-start gap-4"
          >
            <AlertTriangle size={24} className="text-destructive flex-shrink-0 mt-0.5" />
            <div className="space-y-1 text-xs text-muted-foreground leading-relaxed">
              <h3 className="font-bold text-foreground text-sm uppercase tracking-wide">Important Legal Notice</h3>
              <p>
                <strong>THESE TERMS GOVERN YOUR ACCESS TO AND USE OF SIGNANY 2.0. PLEASE READ CAREFULLY BEFORE USING THE SERVICE. BY ACCESSING OR USING THE SERVICE, YOU ACCEPT THESE TERMS IN FULL. IF YOU DO NOT AGREE, YOU MUST NOT USE THE SERVICE.</strong>
              </p>
            </div>
          </motion.div>

          {/* Main Layout: Sticky Sidebar + Content */}
          <div className="grid lg:grid-cols-[280px_1fr] gap-12 items-start">
            {/* Sticky Sidebar Navigation */}
            <aside className="hidden lg:block sticky top-28 space-y-2 max-h-[calc(100vh-120px)] overflow-y-auto pr-2">
              <div className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-4 px-3">
                Table of Contents
              </div>
              <nav className="space-y-1">
                {tableOfContents.map((item) => {
                  const isActive = activeSection === item.id;
                  return (
                    <button
                      key={item.id}
                      onClick={() => scrollToSection(item.id)}
                      className={`w-full text-left px-3 py-2 rounded-xl text-xs font-medium transition-all duration-150 flex items-center justify-between group ${
                        isActive
                          ? "bg-primary text-primary-foreground font-semibold shadow-sm"
                          : "text-muted-foreground hover:bg-muted hover:text-foreground"
                      }`}
                    >
                      <span className="truncate">{item.title}</span>
                      <ChevronRight
                        size={14}
                        className={`transition-transform duration-150 ${
                          isActive ? "opacity-100 translate-x-0" : "opacity-0 -translate-x-1 group-hover:opacity-60"
                        }`}
                      />
                    </button>
                  );
                })}
              </nav>

              <div className="pt-6 border-t border-border mt-6 px-3">
                <div className="p-4 rounded-2xl bg-muted/40 border border-border">
                  <HelpCircle size={20} className="text-primary mb-2" />
                  <p className="text-xs font-bold text-foreground mb-1">Questions about Terms?</p>
                  <p className="text-[11px] text-muted-foreground mb-3 leading-normal">
                    Contact our legal team for any contractual inquiries.
                  </p>
                  <a
                    href="mailto:info@mvclouds.com"
                    className="inline-flex items-center gap-1.5 text-xs font-bold text-primary hover:underline"
                  >
                    <Mail size={12} /> info@mvclouds.com
                  </a>
                </div>
              </div>
            </aside>

            {/* Content Body */}
            <div className="space-y-12 text-foreground">

              {/* 1. Acceptance and Scope */}
              <section id="acceptance" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">1. Acceptance and Scope</h2>

                <p className="text-muted-foreground text-sm leading-relaxed">
                  These Terms and Conditions ("Terms") govern access to and use of SignAny 2.0 (the "Service"), operated by MV Clouds Private Limited ("MV Clouds," "we," "us," "our"). These Terms apply to:
                </p>

                <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground leading-relaxed pl-1">
                  <li>
                    <strong className="text-foreground">Website Visitors:</strong> Visitors who browse our website or documentation without registering an account.
                  </li>
                  <li>
                    <strong className="text-foreground">Account Customers:</strong> Customers who register for an account, whether on the free tier or paid subscription.
                  </li>
                  <li>
                    <strong className="text-foreground">Document Signers:</strong> Signers who receive documents through the Service for signature, with or without an account.
                  </li>
                </ul>

                <p className="text-sm text-muted-foreground leading-relaxed font-semibold pt-1">
                  By accessing or using the Service, you accept these Terms in full. If you do not agree, you must not use the Service.
                </p>
              </section>

              {/* 2. Definitions */}
              <section id="definitions" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">2. Definitions</h2>

                <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground leading-relaxed pl-1">
                  {definitionsList.map((item, idx) => (
                    <li key={idx}>
                      <strong className="text-foreground">{item.term}:</strong> {item.desc}
                    </li>
                  ))}
                </ul>
              </section>

              {/* 3. Eligibility */}
              <section id="eligibility" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">3. Eligibility</h2>

                <p className="text-sm text-muted-foreground leading-relaxed">
                  You must be at least <strong>18 years old</strong>, or the age of majority in your jurisdiction, and have the legal capacity to enter into binding agreements to use the Service, particularly to sign or send Documents for signature.
                </p>
              </section>

              {/* 4. Consumer Disclosure - Electronic Records & Signatures */}
              <section id="consumer-disclosure" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">4. Consumer Disclosure — Electronic Records and Signatures</h2>

                <p className="text-muted-foreground text-sm leading-relaxed">
                  By using the Service, you explicitly consent to:
                </p>

                <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground leading-relaxed pl-1">
                  <li>Conduct business and legal transactions electronically.</li>
                  <li>Receive notices, disclosures, and completed document records electronically rather than on paper.</li>
                  <li>Sign Documents using electronic signatures, which carry the same legal validity as handwritten wet-ink signatures under applicable law (e.g. U.S. ESIGN Act, UETA, EU eIDAS Regulation, India's Information Technology Act, 2000, or equivalent global legislation).</li>
                </ul>

                <p className="text-sm text-muted-foreground leading-relaxed">
                  You may withdraw this consent at any time by contacting <a href="mailto:info@esignany.com" className="text-primary underline">info@esignany.com</a>, though doing so may limit your ability to use the Service. You may request a paper copy of any electronically signed Document by contacting us.
                </p>

                <div className="space-y-1 pt-2">
                  <h3 className="font-semibold text-foreground text-sm">Important Notice on Non-Eligible Document Types</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    Electronic signatures <strong>may not be valid for wills, property deeds, powers of attorney, negotiable instruments, court orders, or land transfer documents</strong> in certain jurisdictions. Please verify the electronic signature laws of your specific jurisdiction with a qualified legal professional before relying on the Service for these document types.
                  </p>
                </div>
              </section>

              {/* 5. Account Registration and Responsibilities */}
              <section id="account-responsibilities" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">5. Account Registration and Responsibilities</h2>

                <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground leading-relaxed pl-1">
                  <li>
                    <strong className="text-foreground">Credential Security:</strong> You are responsible for maintaining the strict confidentiality of your login credentials and for all activity occurring under your Account.
                  </li>
                  <li>
                    <strong className="text-foreground">Unauthorised Access:</strong> You must notify us immediately at <a href="mailto:info@esignany.com" className="text-primary underline">info@esignany.com</a> of any unauthorised access to, or breach of, your Account.
                  </li>
                  <li>
                    <strong className="text-foreground">Accurate Information:</strong> You agree that all information provided during registration and profile updates is accurate, current, and complete.
                  </li>
                  <li>
                    <strong className="text-foreground">Organisational Authority:</strong> If registering on behalf of an organisation, you represent that you have full legal authority to bind that entity to these Terms.
                  </li>
                </ul>
              </section>

              {/* 6. License Grant and Restrictions */}
              <section id="license-grant" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">6. License Grant and Restrictions</h2>

                <div className="space-y-4 text-sm text-muted-foreground leading-relaxed">
                  <div>
                    <h3 className="font-semibold text-foreground text-base mb-1">6.1 Limited License</h3>
                    <p>
                      Subject to these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to access and use the Service for your internal business or personal purposes in accordance with your subscription tier.
                    </p>
                  </div>

                  <div>
                    <h3 className="font-semibold text-foreground text-base mb-1">6.2 Restrictions</h3>
                    <p className="mb-2">You agree NOT to:</p>
                    <ul className="list-disc list-inside space-y-1.5 pl-1">
                      <li>Reproduce, resell, sublicense, or redistribute the Service or any part of it.</li>
                      <li>Reverse engineer, decompile, or attempt to extract the source code of the Service.</li>
                      <li>Use automated bots, scrapers, or crawlers to access the Service without express written approval.</li>
                      <li>Use the Service to design, benchmark, or build a competing product or service.</li>
                    </ul>
                  </div>
                </div>
              </section>

              {/* 7. Your Responsibilities as a User */}
              <section id="user-responsibilities" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">7. Your Responsibilities as a User</h2>

                <p className="text-muted-foreground text-sm leading-relaxed">
                  You represent and warrant that:
                </p>

                <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground leading-relaxed pl-1">
                  <li>
                    <strong className="text-foreground">Legal Signing Authority:</strong> You have full legal authority to sign any Document you sign or send for signature on behalf of yourself or an organisation.
                  </li>
                  <li>
                    <strong className="text-foreground">Signature Authenticity:</strong> All Signature Data and identity details submitted are accurate, truthful, and not fraudulent or misleading.
                  </li>
                  <li>
                    <strong className="text-foreground">No Forgery or Impersonation:</strong> You will not use the Service to forge signatures, impersonate individuals, or upload unauthorized documents.
                  </li>
                  <li>
                    <strong className="text-foreground">Document Legality:</strong> You are solely responsible for the content, accuracy, and legal compliance of Documents you upload or send for signature.
                  </li>
                </ul>
              </section>

              {/* 8. Role of the Service and Signature Validity */}
              <section id="role-of-service" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">8. Role of the Service and Signature Validity</h2>

                <div className="space-y-4 text-sm text-muted-foreground leading-relaxed">
                  <div>
                    <h3 className="font-semibold text-foreground text-base mb-1">8.1 Platform Facilitator (Not a Law Firm)</h3>
                    <p>
                      MV Clouds provides a technology platform to facilitate electronic signing. We do not act as a party to, or guarantor of, any agreement signed using the Service, and we do not review the legal sufficiency or contents of your Documents. <strong>We are not a law firm and do not provide legal advice.</strong>
                    </p>
                  </div>

                  <div>
                    <h3 className="font-semibold text-foreground text-base mb-1">8.2 Audit Trail & Enforceability Factors</h3>
                    <p>
                      Each signed Document is accompanied by a cryptographic Audit Trail intended to support legal enforceability. Enforceability depends on jurisdiction and transaction nature. You are solely responsible for verifying whether your transaction is eligible for electronic signature.
                    </p>
                  </div>
                </div>
              </section>

              {/* 9. Free and Paid Tiers (Freemium) */}
              <section id="freemium" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">9. Free and Paid Tiers (Freemium)</h2>

                <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground leading-relaxed pl-1">
                  <li>
                    <strong className="text-foreground">Starter Tier:</strong> Offers free signature features subject to monthly document quotas and usage limitations as described on our pricing page.
                  </li>
                  <li>
                    <strong className="text-foreground">Business & Enterprise:</strong> Unlocks advanced tools, API access, custom branding, and higher document limits billed according to selected pricing plans.
                  </li>
                </ul>
              </section>

              {/* 10. Payment and Billing */}
              <section id="payment-billing" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">10. Payment and Billing Terms</h2>

                <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground leading-relaxed pl-1">
                  <li>
                    <strong className="text-foreground">10.1 Payment via Stripe:</strong> Payments are processed securely via Stripe. By subscribing, you authorise recurring charges to your payment method.
                  </li>
                  <li>
                    <strong className="text-foreground">10.2 Auto-Renewal:</strong> Subscriptions automatically renew for identical billing periods unless cancelled prior to renewal date via account settings.
                  </li>
                  <li>
                    <strong className="text-foreground">10.3 Non-Refundable:</strong> Payments are non-refundable except where required by applicable law or expressly stated in our Refund Policy.
                  </li>
                  <li>
                    <strong className="text-foreground">10.4 Price Changes:</strong> We may change subscription pricing with 30 days advance notice. Changes take effect on the next renewal cycle.
                  </li>
                  <li>
                    <strong className="text-foreground">10.5 Applicable Taxes:</strong> Fees are exclusive of applicable statutory taxes (e.g. GST, VAT), which will be added at checkout where mandated.
                  </li>
                  <li>
                    <strong className="text-foreground">10.6 Failed Payments:</strong> If payment fails, we reserve the right to suspend access to Paid Features until the account balance is settled.
                  </li>
                </ul>
              </section>

              {/* 11. Document Storage and Retention */}
              <section id="storage-retention" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">11. Document Storage and Retention</h2>

                <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground leading-relaxed pl-1">
                  <li>
                    <strong className="text-foreground">Cloud Storage Infrastructure:</strong> Documents and Audit Trails are stored securely in cloud storage (AWS S3) and retained for 1 year to meet standard legal evidentiary minimums.
                  </li>
                  <li>
                    <strong className="text-foreground">User Backup Responsibility:</strong> You are responsible for downloading and maintaining your own copies of important signed Documents. The Service is not a substitute for your primary records management archive.
                  </li>
                  <li>
                    <strong className="text-foreground">Post Account-Closure Retention:</strong> Upon account closure, completed signature records and Audit Trails may be retained where required by law or to satisfy contractual obligations to other transaction parties.
                  </li>
                </ul>
              </section>

              {/* 12. Acceptable Use */}
              <section id="acceptable-use" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">12. Acceptable Use Policy</h2>

                <p className="text-muted-foreground text-sm font-semibold">You agree NOT to use SignAny 2.0 to:</p>

                <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground leading-relaxed pl-1">
                  <li>Engage in unlawful activities, including financial fraud, signature forgery, or money laundering.</li>
                  <li>Upload Documents containing malware, ransomware, viruses, or destructive code.</li>
                  <li>Attempt unauthorized access to Service servers, other users' Accounts, or private documents.</li>
                  <li>Place undue automated load or disrupt platform operations and cloud infrastructure.</li>
                  <li>Harass, defame, threaten, or infringe upon third-party intellectual property rights.</li>
                </ul>

                <p className="text-xs text-muted-foreground italic pt-1">
                  We reserve the right to suspend or terminate accounts violating this policy immediately.
                </p>
              </section>

              {/* 13. Intellectual Property */}
              <section id="intellectual-property" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">13. Intellectual Property Rights</h2>

                <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground leading-relaxed pl-1">
                  <li>
                    <strong className="text-foreground">13.1 Service Ownership:</strong> All software, interface designs, branding, logos, and code are owned exclusively by MV Clouds Private Limited or its licensors under copyright and IP laws.
                  </li>
                  <li>
                    <strong className="text-foreground">13.2 Customer Document Ownership:</strong> You retain 100% ownership of your Documents. You grant us a limited operational license solely to store, process, and display them to execute transactions requested by you.
                  </li>
                  <li>
                    <strong className="text-foreground">13.3 Trademark Restrictions:</strong> You may not use MV Clouds' or SignAny's trademarks, logos, or brand assets without prior explicit written consent.
                  </li>
                  <li>
                    <strong className="text-foreground">13.4 User Feedback License:</strong> Feedback or suggestions provided regarding the Service grant us a perpetual, royalty-free license to improve our products without compensation obligations.
                  </li>
                </ul>
              </section>

              {/* 14. Confidentiality */}
              <section id="confidentiality" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">14. Confidentiality Obligations</h2>

                <p className="text-muted-foreground text-sm leading-relaxed">
                  Each party agrees to protect the other's confidential information disclosed in connection with the Service using reasonable enterprise care, and not to use or disclose it except as necessary to fulfill obligations under these Terms or as required by law.
                </p>
              </section>

              {/* 15. Disclaimers */}
              <section id="disclaimers" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">15. Warranty Disclaimers</h2>

                <div className="space-y-2 text-sm text-muted-foreground leading-relaxed">
                  <p className="font-bold text-foreground uppercase tracking-wide">"AS IS" and "AS AVAILABLE" Provision</p>
                  <p>
                    THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE, OR THAT ELECTRONICALLY SIGNED DOCUMENTS WILL BE RECOGNIZED AS VALID IN EVERY JURISDICTION OR FOR EVERY DOCUMENT TYPE.
                  </p>
                </div>
              </section>

              {/* 16. Limitation of Liability */}
              <section id="limitation-liability" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">16. Limitation of Liability</h2>

                <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground leading-relaxed pl-1">
                  <li>
                    <strong className="text-foreground">16.1 Indirect Damages Exclusion:</strong> TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, MV CLOUDS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES — INCLUDING LOST PROFITS, LOST DATA, OR BUSINESS INTERRUPTION — ARISING FROM YOUR USE OF THE SERVICE.
                  </li>
                  <li>
                    <strong className="text-foreground">16.2 Total Liability Cap:</strong> OUR TOTAL AGGREGATE LIABILITY FOR ANY CLAIM ARISING OUT OF OR RELATED TO THESE TERMS WILL NOT EXCEED THE TOTAL AMOUNT YOU PAID US IN THE SIX (6) MONTHS PRECEDING THE CLAIM, OR ₹5,000 (INR), WHICHEVER IS GREATER.
                  </li>
                </ul>
              </section>

              {/* 17. Indemnification */}
              <section id="indemnification" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">17. Indemnification</h2>

                <p className="text-muted-foreground text-sm leading-relaxed">
                  You agree to defend, indemnify, and hold harmless MV Clouds, its officers, employees, and agents from any third-party claims, damages, liabilities, and costs (including legal fees) arising from: (a) your breach of these Terms; (b) misuse of the Service; (c) Documents uploaded or signed by you; or (d) your violation of applicable laws.
                </p>
              </section>

              {/* 18. Term and Termination */}
              <section id="termination" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">18. Term and Termination</h2>

                <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground leading-relaxed pl-1">
                  <li>
                    <strong className="text-foreground">18.1 Termination by You:</strong> You may close your Account at any time through account settings or by contacting <a href="mailto:info@esignany.com" className="text-primary underline">info@esignany.com</a>.
                  </li>
                  <li>
                    <strong className="text-foreground">18.2 Termination by Us:</strong> We may suspend or terminate access for violations of Terms, fraudulent activity, or legal compliance.
                  </li>
                </ul>
              </section>

              {/* 19. Dispute Resolution */}
              <section id="dispute-resolution" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">19. Dispute Resolution and Governing Law</h2>

                <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground leading-relaxed pl-1">
                  <li>
                    <strong className="text-foreground">19.1 Informal Resolution:</strong> Contact us at <a href="mailto:info@esignany.com" className="text-primary underline">info@esignany.com</a> first to attempt informal resolution before filing formal legal proceedings.
                  </li>
                  <li>
                    <strong className="text-foreground">19.2 Governing Law:</strong> These Terms are governed by and construed in accordance with the laws of India.
                  </li>
                  <li>
                    <strong className="text-foreground">19.3 Venue & Jurisdiction:</strong> Courts of Ahmedabad, Gujarat, India shall have exclusive jurisdiction / arbitration under the Arbitration and Conciliation Act, 1996.
                  </li>
                </ul>
              </section>

              {/* 20. General Provisions */}
              <section id="general-provisions" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">20. General Provisions</h2>

                <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground leading-relaxed pl-1">
                  <li>
                    <strong className="text-foreground">Entire Agreement:</strong> These Terms, together with our Privacy Policy, constitute the entire agreement regarding the Service.
                  </li>
                  <li>
                    <strong className="text-foreground">Severability & Waiver:</strong> If any provision is held invalid, remaining provisions stay in effect. Failure to enforce is not a waiver.
                  </li>
                  <li>
                    <strong className="text-foreground">Assignment & Force Majeure:</strong> Neither party is liable for delays caused by acts beyond reasonable control (natural disasters, infrastructure outages).
                  </li>
                  <li>
                    <strong className="text-foreground">Updates to Terms:</strong> Material changes will be notified 30 days in advance via email or in-service notification.
                  </li>
                </ul>
              </section>

              {/* 21. Supplemental Terms for India */}
              <section id="supplemental-india" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">21. Supplemental Terms for India</h2>

                <div className="space-y-2 text-sm text-muted-foreground leading-relaxed">
                  <p className="font-semibold text-foreground">Statutory Disclosures for Indian Domiciled Users:</p>
                  <ul className="list-disc list-inside space-y-1.5 pl-1">
                    <li>Nothing in these Terms limits your statutory rights under the <strong>Consumer Protection Act, 2019</strong>.</li>
                    <li>Electronic signatures executed through the Service satisfy the requirements of India's <strong>Information Technology Act, 2000</strong> and its underlying rules.</li>
                    <li>Courts in <strong>Ahmedabad, Gujarat</strong> hold exclusive jurisdiction over disputes.</li>
                  </ul>
                </div>
              </section>

              {/* 22. Contact Us */}
              <section id="contact-us" className="scroll-mt-28 space-y-4">
                <h2 className="text-xl md:text-2xl font-bold text-foreground">22. Contact Information</h2>

                <div className="space-y-3 text-sm text-muted-foreground leading-relaxed">
                  <div>
                    <h3 className="text-base font-bold text-foreground">MV Clouds Private Limited</h3>
                    <p className="text-xs text-muted-foreground">Operator of SignAny 2.0</p>
                  </div>

                  <div>
                    <strong className="text-foreground block">Registered Headquarters:</strong>
                    D - 404, The First Synthesis, B/H Keshavbaug Party Plot, Ahmedabad, Gujarat - 380015, India
                  </div>

                  <div>
                    <strong className="text-foreground block">Legal & Contract Inquiries:</strong>
                    <div className="space-x-3 pt-1">
                      <a href="mailto:info@mvclouds.com" className="text-primary font-semibold hover:underline">
                        info@mvclouds.com
                      </a>
                      <span>|</span>
                      <a href="mailto:info@esignany.com" className="text-primary font-semibold hover:underline">
                        info@esignany.com
                      </a>
                    </div>
                  </div>
                </div>
              </section>

            </div>
          </div>
        </div>
      </main>

      {/* Floating Back to Top Button */}
      {showBackToTop && (
        <button
          onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
          className="fixed bottom-6 right-6 z-40 p-3 rounded-full bg-primary text-primary-foreground shadow-lg hover:scale-110 transition-all duration-200"
          aria-label="Back to top"
        >
          <ArrowUp size={18} />
        </button>
      )}

      <Footer />
    </div>
  );
};

export default TermsAndConditions;
