/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as HashVerificationRouteImport } from './routes/hash-verification'
import { Route as LifecycleRouteImport } from './routes/lifecycle'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as UserGuideRouteImport } from './routes/user-guide'
import { Route as VerifyHashRouteImport } from './routes/verifyHash'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as FeaturesIdRouteImport } from './routes/features_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const HashVerificationRoute = HashVerificationRouteImport.update({
  id: '/hash-verification',
  path: '/hash-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleRoute = LifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const UserGuideRoute = UserGuideRouteImport.update({
  id: '/user-guide',
  path: '/user-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyHashRoute = VerifyHashRouteImport.update({
  id: '/verifyHash',
  path: '/verifyHash',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIdRoute = FeaturesIdRouteImport.update({
  id: '/features_/$id',
  path: '/features/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/blog': typeof BlogRoute
  '/contact-us': typeof ContactUsRoute
  '/faqs': typeof FaqsRoute
  '/features': typeof FeaturesRoute
  '/hash-verification': typeof HashVerificationRoute
  '/lifecycle': typeof LifecycleRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/user-guide': typeof UserGuideRoute
  '/verifyHash': typeof VerifyHashRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/features/$id': typeof FeaturesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/blog': typeof BlogRoute
  '/contact-us': typeof ContactUsRoute
  '/faqs': typeof FaqsRoute
  '/features': typeof FeaturesRoute
  '/hash-verification': typeof HashVerificationRoute
  '/lifecycle': typeof LifecycleRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/user-guide': typeof UserGuideRoute
  '/verifyHash': typeof VerifyHashRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/features/$id': typeof FeaturesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/blog': typeof BlogRoute
  '/contact-us': typeof ContactUsRoute
  '/faqs': typeof FaqsRoute
  '/features': typeof FeaturesRoute
  '/hash-verification': typeof HashVerificationRoute
  '/lifecycle': typeof LifecycleRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/user-guide': typeof UserGuideRoute
  '/verifyHash': typeof VerifyHashRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/features_/$id': typeof FeaturesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/blog'
    | '/contact-us'
    | '/faqs'
    | '/features'
    | '/hash-verification'
    | '/lifecycle'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/user-guide'
    | '/verifyHash'
    | '/blog/$slug'
    | '/features/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/blog'
    | '/contact-us'
    | '/faqs'
    | '/features'
    | '/hash-verification'
    | '/lifecycle'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/user-guide'
    | '/verifyHash'
    | '/blog/$slug'
    | '/features/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/blog'
    | '/contact-us'
    | '/faqs'
    | '/features'
    | '/hash-verification'
    | '/lifecycle'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/user-guide'
    | '/verifyHash'
    | '/blog_/$slug'
    | '/features_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BlogRoute: typeof BlogRoute
  ContactUsRoute: typeof ContactUsRoute
  FaqsRoute: typeof FaqsRoute
  FeaturesRoute: typeof FeaturesRoute
  HashVerificationRoute: typeof HashVerificationRoute
  LifecycleRoute: typeof LifecycleRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  UserGuideRoute: typeof UserGuideRoute
  VerifyHashRoute: typeof VerifyHashRoute
  BlogSlugRoute: typeof BlogSlugRoute
  FeaturesIdRoute: typeof FeaturesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hash-verification': {
      id: '/hash-verification'
      path: '/hash-verification'
      fullPath: '/hash-verification'
      preLoaderRoute: typeof HashVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle': {
      id: '/lifecycle'
      path: '/lifecycle'
      fullPath: '/lifecycle'
      preLoaderRoute: typeof LifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-guide': {
      id: '/user-guide'
      path: '/user-guide'
      fullPath: '/user-guide'
      preLoaderRoute: typeof UserGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifyHash': {
      id: '/verifyHash'
      path: '/verifyHash'
      fullPath: '/verifyHash'
      preLoaderRoute: typeof VerifyHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features_/$id': {
      id: '/features_/$id'
      path: '/features/$id'
      fullPath: '/features/$id'
      preLoaderRoute: typeof FeaturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BlogRoute: BlogRoute,
  ContactUsRoute: ContactUsRoute,
  FaqsRoute: FaqsRoute,
  FeaturesRoute: FeaturesRoute,
  HashVerificationRoute: HashVerificationRoute,
  LifecycleRoute: LifecycleRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  UserGuideRoute: UserGuideRoute,
  VerifyHashRoute: VerifyHashRoute,
  BlogSlugRoute: BlogSlugRoute,
  FeaturesIdRoute: FeaturesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
