/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as LifecycleRouteImport } from './routes/lifecycle'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as VerifyHashRouteImport } from './routes/verifyHash'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as UseCasesIdRouteImport } from './routes/use-cases_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleRoute = LifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyHashRoute = VerifyHashRouteImport.update({
  id: '/verifyHash',
  path: '/verifyHash',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesIdRoute = UseCasesIdRouteImport.update({
  id: '/use-cases_/$id',
  path: '/use-cases/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/blog': typeof BlogRoute
  '/faqs': typeof FaqsRoute
  '/lifecycle': typeof LifecycleRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/use-cases': typeof UseCasesRoute
  '/verifyHash': typeof VerifyHashRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/use-cases/$id': typeof UseCasesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/blog': typeof BlogRoute
  '/faqs': typeof FaqsRoute
  '/lifecycle': typeof LifecycleRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/use-cases': typeof UseCasesRoute
  '/verifyHash': typeof VerifyHashRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/use-cases/$id': typeof UseCasesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/blog': typeof BlogRoute
  '/faqs': typeof FaqsRoute
  '/lifecycle': typeof LifecycleRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/use-cases': typeof UseCasesRoute
  '/verifyHash': typeof VerifyHashRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/use-cases_/$id': typeof UseCasesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/blog'
    | '/faqs'
    | '/lifecycle'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/use-cases'
    | '/verifyHash'
    | '/blog/$slug'
    | '/use-cases/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/blog'
    | '/faqs'
    | '/lifecycle'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/use-cases'
    | '/verifyHash'
    | '/blog/$slug'
    | '/use-cases/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/blog'
    | '/faqs'
    | '/lifecycle'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/use-cases'
    | '/verifyHash'
    | '/blog_/$slug'
    | '/use-cases_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BlogRoute: typeof BlogRoute
  FaqsRoute: typeof FaqsRoute
  LifecycleRoute: typeof LifecycleRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  UseCasesRoute: typeof UseCasesRoute
  VerifyHashRoute: typeof VerifyHashRoute
  BlogSlugRoute: typeof BlogSlugRoute
  UseCasesIdRoute: typeof UseCasesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle': {
      id: '/lifecycle'
      path: '/lifecycle'
      fullPath: '/lifecycle'
      preLoaderRoute: typeof LifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifyHash': {
      id: '/verifyHash'
      path: '/verifyHash'
      fullPath: '/verifyHash'
      preLoaderRoute: typeof VerifyHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases_/$id': {
      id: '/use-cases_/$id'
      path: '/use-cases/$id'
      fullPath: '/use-cases/$id'
      preLoaderRoute: typeof UseCasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BlogRoute: BlogRoute,
  FaqsRoute: FaqsRoute,
  LifecycleRoute: LifecycleRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  UseCasesRoute: UseCasesRoute,
  VerifyHashRoute: VerifyHashRoute,
  BlogSlugRoute: BlogSlugRoute,
  UseCasesIdRoute: UseCasesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
